//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "collections")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub description: Option<String>,
    pub created: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collection_creators::Entity")]
    CollectionCreators,
    #[sea_orm(has_many = "super::collection_tags::Entity")]
    CollectionTags,
    #[sea_orm(has_many = "super::media_collection::Entity")]
    MediaCollection,
}

impl Related<super::collection_creators::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionCreators.def()
    }
}

impl Related<super::collection_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionTags.def()
    }
}

impl Related<super::media_collection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaCollection.def()
    }
}

impl Related<super::creators::Entity> for Entity {
    fn to() -> RelationDef {
        super::collection_creators::Relation::Creators.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::collection_creators::Relation::Collections
                .def()
                .rev(),
        )
    }
}

impl Related<super::media::Entity> for Entity {
    fn to() -> RelationDef {
        super::media_collection::Relation::Media.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::media_collection::Relation::Collections.def().rev())
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::collection_tags::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::collection_tags::Relation::Collections.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
