//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "creator_alias")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub creator: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub alias: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::creators::Entity",
        from = "Column::Creator",
        to = "super::creators::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Creators,
}

impl Related<super::creators::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Creators.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
