//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub mod prelude;

pub mod collection_creators;
pub mod collection_tags;
pub mod collections;
pub mod creator_alias;
pub mod creators;
pub mod media;
pub mod media_collection;
pub mod media_creators;
pub mod media_tags;
pub mod sea_orm_active_enums;
pub mod sources;
pub mod tag_groups;
pub mod tags;
