//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::collection_creators::Entity as CollectionCreators;
pub use super::collection_tags::Entity as CollectionTags;
pub use super::collections::Entity as Collections;
pub use super::creators::Entity as Creators;
pub use super::media::Entity as Media;
pub use super::media_collection::Entity as MediaCollection;
pub use super::media_creators::Entity as MediaCreators;
pub use super::media_tags::Entity as MediaTags;
pub use super::sources::Entity as Sources;
pub use super::tag_groups::Entity as TagGroups;
pub use super::tags::Entity as Tags;
