[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[lib]
name = "entity"
path = "src/mod.rs"

[dependencies]
sea-orm = { version = "1.1.10", features = [ 'sqlx-postgres', 'runtime-tokio-rustls', "macros" ] }
serde = { version = "1.0.219", features = ["derive"] }